version: "3.9"

services:
  server:
    build: "."
    container_name: "image-gallery-server"
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - psdb
    networks:
      - image-gallery

  psdb:
    image: postgres
    container_name: "image-gallery-psdb"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 12345678
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "image-gallery"
    networks:
      - image-gallery

  envoy:
    build: "./envoy"
    container_name: "image-gallery-envoyproxy"
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - server
    networks:
      - image-gallery

  client:
    build: "./client"
    container_name: "image-gallery-client"
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - envoy
    networks:
      - image-gallery

networks:
  image-gallery:
    driver: bridge